### ISSUE TITLE
Target administration css

### ISSUE THREAD

**Issue by m00n22** [dneustadt/DneCustomCssJs#2]
Hi there,

First of all, love the plugin! It's not an issue, more a question, is it possible to transform this plugin to target the administration side instead of the storefront. I would like to use it to brand the login screen.

**Comment by dneustadt** [comment]
Hi,
even though I like the idea, handling and compilation of assets differs too much within the administration module to be a feasible feature for this plugin. What I will consider though is providing a new plugin specifically for injecting assets into the administration. If I get around to do so I will let you know with another reply to this issue.
