### ISSUE TITLE
Limit Snippets to sale channels or themes

### ISSUE THREAD

**Issue by roben** [dneustadt/DneCustomCssJs#4]
Thanks for this great extension! 

Would it be possible to limit the containers to certain sale channels or themes, though? That's whats currently keeping us from using it, as we have several sale channels using different layouts in our shopware installation.

I would not complain if this feature was only in a paid version of the plugin :)

**Comment by dneustadt** [comment]
Enhancements of the user interface to that extend are currently not on the table, for reasons of maintainability, ease of use and necessity for the majority of users. Instead I encourage the use of a combination of specific DOM elements, SCSS parent selectors and JavaScript conditions regarding sales channel/theme specific style properties and/or JS execution. For that reason I provide a lightweight complimentary plugin that will add specific classes to the `body` tag: [DneBodyClasses](https://github.com/dneustadt/DneBodyClasses)

**Comment by roben** [comment]
That's totally fine! Thanks
