### ISSUE TITLE
Update not possible in SW6

### ISSUE THREAD

**Issue by reutli** [dneustadt/DneCustomCssJs#8]
Tried to update in SW6.
Update is not working at all. Clicking on "Aktualisieren" is not working?
When I'm clicking nothing's happening.

Issue on my side?
<img width="853" alt="Bildschirmfoto 2020-12-14 um 18 03 58" src="https://user-images.githubusercontent.com/62477965/102111508-c76e9000-3e36-11eb-9108-f7c0433321d4.png">

**Comment by dneustadt** [comment]
That's not an issue with this plugin but a Shopware related bug. Please report at the associated repository: https://github.com/shopware/platform/issues

**Comment by reutli** [comment]
ok, but how should/can I update the PlugIn? Thats not mentioned in the closure...
Bug has been reported tp Shopware
