### ISSUE TITLE
Extending the scssphp compiler should be avoided

### ISSUE THREAD

**Issue by stof** [dneustadt/DneCustomCssJs#9]
hi. I'm one of the scssphp maintainers.

Currently, `Dne\CustomCssJs\Components\Compiler` extends the `ScssPhp\ScssPhp\Compiler` class.
To ease the maintenance of the scssphp library (allowing us to rewrite its internals entirely), we would like to forbid extending the compiler as part of our 2.0 release (in 1.x, almost everything is protected, so any refactoring risks breaking BC).
It would be great if you could refactor your code to avoid relying on extending our compiler (according to https://packanalyst.com/class?q=ScssPhp%5CScssPhp%5CCompiler, your class is the only remaining one extending our compiler in packages available on packagist.org, as we already worked with others).

**Comment by dneustadt** [comment]
Hey,
first of all thanks for the heads-up, very much appreciated! Problem is, chances are I won't be able to do make that change. This is an extension for the e-commerce platform Shopware, hence I'm kinda relying on them to give me some kind of entry point to feed some scss to the compiler. As of now extending the Compiler and replacing it as a service is the only possibility. Unfortunately Shopware is kinda notorious for being slow or unresponsive with pull requests. I seriously doubt I could get them to approve changes in time. Based on download numbers from Shopware's extension marketplace I estimate the active user base for this plugin to be above 1000, many relying on this extension's features, so it would kinda suck to drop compatibility for future Shopware versions depending on your 2.0 release. So I guess this is out of the question... but maybe... could you not? (lol) Seriously though, I'm not sure I can actually do something about this. I mean I will try but I guess this might be the end of the line for this project. Regardless of the issue at hand I'd be genuinely be interested why you would want to do this. I feel like ScssPhp is mostly used as a dependency within larger platforms and/or frameworks. As I understand it, the reason you want to keep people from extending the Class is to keep support inquiries manageable while you do some refactoring. Personally, as part of your target audience, I'd still rather have the freedom of use and live with the possible consequences, than being held back by safety measures. Then again the only method I see any kind of need to get into is `compile`. Maybe there's the possibility to factor out everything else and just have a class with the `compile` method being extendable? Well, nvm, I really don't feel like I should make any suggestions here. Thanks for providing this great piece of software btw, can't imagine the work that went into it.

**Comment by stof** [comment]
Yeah, looking at the fact that you only extend the public method to change the input before calling the parent method, there could be a way to keep your own usage working: change all our internals to use `private` visibility everywhere, but don't mark the class as `final`.

> Regardless of the issue at hand I'd be genuinely be interested why you would want to do this. I feel like ScssPhp is mostly used as a dependency within larger platforms and/or frameworks. As I understand it, the reason you want to keep people from extending the Class is to keep support inquiries manageable while you do some refactoring. Personally, as part of your target audience, I'd still rather have the freedom of use and live with the possible consequences, than being held back by safety measures.

Well, the target audience is also complaining loud when a new release of scssphp breaks their plugin. To us maintainers, this leaves only a few choices:
1. freeze the library, keeping it an incomplete non-compliant implementation of Sass forever (and less and less compliant over time as Sass evolves).
2. lock down the library to enforce the usage of supported extension points, allowing us to do whatever we want in the rest of the codebase as long as we maintain backward compatibility on those extension points (which are **not** based on inheritance, as that's the worse way to provide a maintainable extension point)
3. release each change as a semver-major
4. take over the maintenance of all scssphp-based plugins for all platforms out there, so that we can update them each time we change the internals (before users of these platforms report issues about incompatibility), either to upgrade to new major versions (if following the previous point) or due to not following semver anymore. That option will not happen. We don't have the resources or the will for that (I don't want to maintain plugins for platforms I won't ever use).

We decided to go with option 2 (which still requires a semver-major release when locking things down) rather than option 3, as option 3 is actually worse for downstream users.
Option 1 was considered a bad fit as we received feature request to support newer Sass features already (but becoming fully spec compliant will take time).

**Comment by stof** [comment]
We don't have any estimate yet.

We have a big refactoring of values, which is in progress. This refactoring will impact the extension point for custom functions and custom variables, so a major version will be required to get rid of the old API entirely. I'm not sure yet whether this refactoring can be merged in 1.x without BC breaks. If the answer is yes, the 2.0 release will be delayed (as we will be able to make many changes in 1.x and then remove the BC layer in 2.0). If the answer is no, 2.0 will happen quite soon to allow us to move forward with the refactorings (my current guess is that we need to do a 2.0 release locking the API before landing the refactoring though).

Migrating to 2.0 should be a very easy for projects that don't extend the Compiler though, as the API will stay mostly the same (minus the few methods that are already deprecated of course). We will also keep support for PHP 5.6+ (as today) so that we don't force plugins to drop support for some PHP versions to update, as we definitely want them to upgrade (I would have loved to bump the PHP requirement to a higher version, to be honest)

And in your case, you will still have time until Shopware updates their scssphp dependency, which seems to be low on their radar as they are still using 1.0.6, which is more than 1 year old...
